language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install coinor-cbc

install:
  - pip install .[datapackage]
  - pip install coveralls

# command to run tests
script:
  - nosetests --with-doctest --with-coverage -c nose.cfg

after_success:
  - coveralls
